#!/usr/bin/env node
/**
 * Concatenate the design-token layers + base reset into the single shippable
 * stylesheet `styles/twico-ui.css` (what consumers import as `twico-ui/styles.css`).
 *
 * This file used to be maintained by hand, which let it drift from the real
 * `tokens/*.css` + `base.css` sources. Now it is generated:
 *   npm run build:css          regenerate it
 *   npm run build:css -- --check   fail (exit 1) if it is stale (used in CI)
 *
 * The only transform vs. the sources is the @font-face url(): the dev sources
 * point at `../assets/fonts/`; in the published package the fonts ship beside
 * this stylesheet in `./fonts/`.
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "styles", "twico-ui.css");

// Order matters: fonts first (so @font-face is defined), then tokens, then base.
const LAYERS = [
  "tokens/fonts.css",
  "tokens/colors.css",
  "tokens/typography.css",
  "tokens/spacing.css",
  "tokens/radius.css",
  "tokens/motion.css",
  "base.css",
];

const HEADER = `/* ============================================================
   twico-ui — bundled stylesheet (design tokens + base reset + webfonts)
   Import ONCE at your app root:   import "twico-ui/styles.css";
   Dark mode:  add class="dark" (or data-theme="dark") to <html>.
   Fonts ship beside this file in ./fonts/ (self-hosted, OFL).

   GENERATED by scripts/build-css.mjs from tokens/*.css + base.css —
   do not edit by hand; run \`npm run build:css\` after editing a source.
   ============================================================ */
`;

async function generate() {
  const parts = [HEADER];
  for (const rel of LAYERS) {
    let css = await readFile(join(ROOT, rel), "utf8");
    if (rel === "tokens/fonts.css") {
      // Dev sources reference ../assets/fonts/; the package ships fonts in ./fonts/.
      css = css.replace(/\.\.\/assets\/fonts\//g, "./fonts/");
    }
    parts.push(`\n/* ===== ${rel} ===== */\n${css.trimEnd()}\n`);
  }
  return parts.join("");
}

const next = await generate();
const check = process.argv.includes("--check");

if (check) {
  let current = "";
  try {
    current = await readFile(OUT, "utf8");
  } catch {}
  if (current.replace(/\r\n/g, "\n") !== next.replace(/\r\n/g, "\n")) {
    console.error(
      "✗ styles/twico-ui.css is stale. Run `npm run build:css` and commit the result."
    );
    process.exit(1);
  }
  console.log("✓ styles/twico-ui.css is up to date.");
} else {
  await writeFile(OUT, next, "utf8");
  console.log("✓ Wrote styles/twico-ui.css from " + LAYERS.length + " sources.");
}
